### ISSUE TITLE
[wf2/summit] ddlrun is failing

### ISSUE THREAD

**Issue by lee212** [2019-ncovgroup/DrugWorkflows#20]
Copy of the ticket to OLCF:

```
bsub -W 10 -nnodes 1 -P med110 -Is bash
Job <90290> is submitted to default queue <batch>.
<<Waiting for dispatch ...>>
<<Starting on batch3>>
(base) bash-4.2$ module load ibm-wml-ce
(ibm-wml-ce-1.7.0-2) bash-4.2$ ddlrun python $CONDA_PREFIX/horovod/examples/tensorflow2_synthetic_benchmark.py
[ERROR DDL-2-0] Unexpected Error: Mapping key not found.
Traceback (most recent call last):
 File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/bin/ddlrun", line 35, in main
   args = inputs.read_args(initial_args)
 File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/lib/python3.6/site-packages/ddlrun/inputs.py", line 463, in read_args
   args.host_list = rankfile.parse_lsf_hosts()
 File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/lib/python3.6/site-packages/ddlrun/rankfile.py", line 200, in parse_lsf_hosts
   hosts = utilities.LSFUtils.get_compute_hosts()
 File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/lib/python3.6/site-packages/ddlrun/utilities.py", line 292, in get_compute_hosts
   return LSFUtils.get_allocation_info()["compute_nodes"]
 File "/sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.7.0-2/lib/python3.6/site-packages/ddlrun/utilities.py", line 286, in get_allocation_info
   LSFUtils._csm_allocation_info["compute_nodes"].sort()
KeyError: 'compute_nodes'
Please see /tmp/DDLRUN/DDLRUN.DXc0i2nGUxxv/ddlrun.log for detailed log.
```

The context is ddlrun is a launcher of horovod on Summit. Without it, it has to be manually prepared to setup gpu devices.

**Comment by lee212** [comment]
The responded message:

> On May 12, 2020, at 12:23 PM, liuh via RT <help@nccs.gov> wrote:

I can reproduce the same error. We have contacted IBM. We are working with IBM
to get it fixed. I will keep you updated.

**Comment by lee212** [comment]
This may become an obstacle running the horovod CVAE.

**Comment by lee212** [comment]
working on to bypass ddlrun. jsrun with a erf file can be a quick resolution.

**Comment by lee212** [comment]
OLCF ticket was not updated since then but this is no longer required to investigate as modified jsrun can replace task placement for horovod.
